//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOVIMIENTOS
    {
        public int ID { get; set; }
        public Nullable<int> PROD_ID { get; set; }
        public Nullable<System.DateTime> MOV_FEC_ENTRADA { get; set; }
        public string MOV_USR_ENTRADA { get; set; }
        public Nullable<System.DateTime> MOV_FEC_SALIDA { get; set; }
        public string MOV_USR_SALIDA { get; set; }
    
        public virtual TBL_PRODUCTOS TBL_PRODUCTOS { get; set; }
    }
}
