//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_UBICACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_UBICACIONES()
        {
            this.TBL_PRODUCTOS = new HashSet<TBL_PRODUCTOS>();
        }
    
        public int ID { get; set; }
        public string UBIC_PASILLO { get; set; }
        public string UBIC_SECCION { get; set; }
        public string UBIC_NIVEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTOS> TBL_PRODUCTOS { get; set; }
    }
}
