//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PROVEEDORES()
        {
            this.TBL_PRODUCTOS = new HashSet<TBL_PRODUCTOS>();
        }
    
        public int ID { get; set; }
        public string PROV_DESCRIP { get; set; }
        public string PROV_NUM_IDENT { get; set; }
        public string PROV_TEL1 { get; set; }
        public string PROV_TEL2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PRODUCTOS> TBL_PRODUCTOS { get; set; }
    }
}
