//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PRODUCTOS()
        {
            this.TBL_MOVIMIENTOS = new HashSet<TBL_MOVIMIENTOS>();
        }
    
        public int ID { get; set; }
        public string PROD_DESCRIP { get; set; }
        public Nullable<int> TIPO_ID { get; set; }
        public string PROD_MODELO { get; set; }
        public Nullable<int> PROV_ID { get; set; }
        public Nullable<int> UBIC_ID { get; set; }
        public Nullable<decimal> PROD_PRECIO { get; set; }
        public Nullable<decimal> PROD_COSTO { get; set; }
        public byte[] IMG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MOVIMIENTOS> TBL_MOVIMIENTOS { get; set; }
        public virtual TBL_PROVEEDORES TBL_PROVEEDORES { get; set; }
        public virtual TBL_TIPOS TBL_TIPOS { get; set; }
        public virtual TBL_UBICACIONES TBL_UBICACIONES { get; set; }
    }
}
